language: node_js
node_js:
  - "16.13.0"
jdk:
  - oraclejdk8
addons:
  sonarcloud: true
script:
  - npm run cover
  - sonar-scanner -Dsonar.login=$SONAR_TOKEN -Dsonar.organization=vik-z -Dsonar.projectKey=ArquitecturaDeSoftware -Dsonar.sources='./app' -X
after_succes:
  - npm run coveralls
install:
  - 'npm i'