language: node_js
node_js:
  - "16.13.0"
jdk:
  - oraclejdk8
addons:
  sonarcloud: true
script:
- sonar-scanner -Dsonar.login=$SONAR_TOKEN -Dsonar.oragnization=vik-z -Dsonar.projectKey=calculator -Dsonar.sources='./app' -X
